---



- name: Check that the db directory exists
  stat:
    path: "{{ frds_ds_config_instance_path }}/db"
  register: frds_db_instance_result

- name: set installed fact
  set_fact:   
    frds_ds_installed: "{{ frds_db_instance_result.stat.exists }}"

- name: debug
  debug:
    msg: "{{ frds_ds_installed }}"

- name: move archive to correct location
  command: "mv {{ frds_staging_dir }}/{{ archive_contents.files[0].split('/')[0] }} {{ frds_ds_install_directory }}"
  become_user: "{{ frds_ds_user }}"
  args:
    creates: "{{ frds_ds_install_directory }}/setup"

- name: "Change ownership of {{ frds_ds_install_directory }} to {{ frds_ds_user }} user"
  file: 
    path: "{{ frds_ds_install_directory }}" 
    owner: "{{ frds_ds_user }}"
    group: "{{ frds_ds_group }}"
    state: directory 
    recurse: yes      

- include_tasks: configureCommandLine.yml
  when: "not frds_ds_installed"

- name: debug
  debug:
    msg: "{{ frds_command_line }}"
  when: "not frds_ds_installed"

- name: setup FRDS
  command: "{{ frds_ds_install_directory }}/setup directory-server {{ frds_command_line }}"
  become_user: "{{ frds_ds_user }}"
  when: "not frds_ds_installed"          

- name: set frds_service_name fact
  set_fact:
    frds_service_name: "{{ frds_ds_service_name }}"
    frds_user: "{{ frds_ds_user }}"

- name: Create systemd script - CentOS/RHEL 6
  template: 
    src: "etc/init.d/{{ frds_ds_service_name }}" 
    dest: "/etc/init.d"
    mode: 0755
  when: ansible_distribution_major_version == '6'

- name: Create systemd script - CentOS/RHEL 7
  template: 
    src: "etc/systemd/system/opends.service.j2" 
    dest: "/etc/systemd/system/{{ frds_ds_service_name }}.service"
    mode: 0755
  when: ansible_distribution_major_version == '7'   