---

- name: Perform Replication Commands
  frds_replication:
    admin_password: "{{ frds_ds_config_replication_admin_password }}"
    base_dn: "{{ frds_ds_config_base_dns }}"
    directory_server_admin_port: "{{ frds_ds_config_replication_server1_admin_port }}" 
    directory_server_bind_password: "{{ frds_ds_config_replication_server1_admin_password }}" 
    directory_server_hostname: "{{  frds_ds_config_replication_server1_hostname }}"
    directory_server_replication_port: "{{ frds_ds_config_replication_server1_replication_port }}"
    frds_bin_dir: "{{ frds_ds_install_directory }}/bin"
    replication_server_admin_port: "{{ frds_ds_config_replication_server2_admin_port }}" 
    replication_server_bind_password: "{{ frds_ds_config_replication_server2_admin_password }}" 
    replication_server_hostname: "{{ frds_ds_config_replication_server2_hostname }}"
    replication_server_replication_port: "{{ frds_ds_config_replication_server2_replication_port }}"
    embedded_replication_server: "{{ frds_ds_config_replication_embedded_server }}"
    state: "{{ item }}"
  loop: "{{ frds_ds_config_replication_states }}"
